[tox]
isolated_build = true
minversion = 4.13.0
envlist =
    py{310,311,312,313,314}
    lint
    format-check
    type-check

[testenv]
description = run the test suite
deps =
    coverage
    pytest
commands =
    pytest --verbose
setenv =
    TEST_INT=5

[testenv:lint]
basepython = python3
skip_install = true
deps =
    flake8 >= 7.1.1, <8
    flake8-docstrings >= 1.5.0, <2
    pep8-naming >= 0.10.0, <1
    flake8-colors >= 0.1.6, <1
    pydocstyle == 5.0.2
commands =
    flake8 --max-line-length 99 src/envarify setup.py

[testenv:type-check]
basepython = python3
deps =
    mypy == 1.15.0
commands =
    mypy --no-incremental src/envarify tests/types_test.py

[testenv:format]
basepython = python3
description = format source code
deps = black == 24.2.0
       isort[pyproject] == 5.13.2
       seed-isort-config >= 1.2.0
extras =
skip_install = true
commands =
    - seed-isort-config --application-directories src,tests
    black src tests setup.py
    isort src tests setup.py

[testenv:format-check]
basepython = python3
description = check that the source code is well formatted
deps = {[testenv:format]deps}
skip_install = {[testenv:format]skip_install}
extras = {[testenv:format]extras}
commands =
    seed-isort-config --application-directories src,tests
    black --diff --check src tests setup.py
    isort --diff --check-only src tests setup.py

[coverage:run]
source =
    src/envarify

[coverage:report]
exclude_lines =
    pragma: no cover
